spring.datasource.url = jdbc:mysql://bd9e97057b1484:596f1bbf@eu-cdbr-west-02.cleardb.net/heroku_0263557f54e812f?reconnect=true
spring.datasource.username = bd9e97057b1484
spring.datasource.password = 596f1bbf
domain.datasource.driver-class=com.mysql.jdbc.Driver


## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update


#  ************** My local database ************************
#spring.datasource.url = jdbc:mysql://localhost:3306/users?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#spring.datasource.username = root
#spring.datasource.password = root

#  ************** Heroku ********************
#spring.datasource.url = jdbc:mysql://bd9e97057b1484:596f1bbf@eu-cdbr-west-02.cleardb.net/heroku_0263557f54e812f?reconnect=true
#spring.datasource.username = bd9e97057b1484
#spring.datasource.password = 596f1bbf




